### ISSUE TITLE
mathcal 中自动打下好像有一些问题

### ISSUE THREAD

**Issue by aqlkzf** [OrangeX4/OrangeX4-HyperSnips#1]
![image](https://user-images.githubusercontent.com/67051837/117951052-5d570a00-b346-11eb-9a68-f9a59c7861cc.png)
请问巨佬可以给一下修改方案吗？

**Comment by OrangeX4** [comment]
是不是 Markdown 暂时还不支持这个符号啊

**Comment by aqlkzf** [comment]
哦哦 那我先去掉使用。 谢谢啦

**Comment by WetABQ** [comment]
在 71816d210580739f5e3544d74bc7fbfbe8e276c7 中修复
可以查看  #5 分支，同样包含了修复
