### ISSUE TITLE
请问想要添加支持数学模式的语言应该如何修改？

### ISSUE THREAD

**Issue by Purkinje-cell** [OrangeX4/OrangeX4-HyperSnips#13]
我想加一个对Rmarkdown文件格式的支持，不知道能不能比较简单的修改一下源码得到？

**Comment by OrangeX4** [comment]
你试着建立一个 `rmarkdown.hsnips` 文件，然后复制 `markdown.hsnips` 的内容进去试试？

理论上 `xxx.hsnips` 文件对应的就是 `xxx` 语言的自动补全。

**Comment by Purkinje-cell** [comment]
emmm，Rmarkdown能够正常展开snippets，但是不能识别数学模式，就是加了m也会在正常写的时候自动展开

**Comment by OrangeX4** [comment]
我没用过 Rmarkdown，也不太清楚是什么 bug 欸，抱歉 :-(

**Comment by Purkinje-cell** [comment]
emmm，我试了一下改源代码，在源代码里面把Rmd加进去就可以了
