### ISSUE TITLE
HyperSnips for Math报个bug

### ISSUE THREAD

**Issue by tmzqcn** [OrangeX4/OrangeX4-HyperSnips#16]
大佬，HyperSnips for Math报个bug，设置好您提供的   https://github.com/OrangeX4/OrangeX4-HyperSnips文件，但是$ $里无法快捷输入您提供的这个，比如...在 正常文本环境和()、[]里都可以快捷输入，但是$ $中不行，这个环境是我主要用的，一直无法快捷输入有点郁闷。。

**Comment by tmzqcn** [comment]
我发现了这个奇怪的问题，就是我说的这个bug，在我根目录下的文档是正常的，然后在一级子目录下就不正常了，出现我说的bug，再到二级子目录下又正常了。。。这bug是不是和之前fix \$有关呢？

我是直接全部复制的HyperSnips文件，那我再分开复制试一试看看，感谢您的回答！



在 2022-12-05 23:19:19，"OrangeX4" ***@***.***> 写道：

你是不是复制错了？我这里是正常的。


你也可以删除一部分，慢慢地拍错。



---Original---
From: ***@***.***&gt;
Sent at: 2022年12月5日(Mon) Evening10:14
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [OrangeX4/OrangeX4-HyperSnips] HyperSnips for Math报个bug (Issue #16)





大佬，HyperSnips for Math报个bug，设置好您提供的 https://github.com/OrangeX4/OrangeX4-HyperSnips文件，但是$ $里无法快捷输入您提供的这个，比如...在 正常文本环境和()、[]里都可以快捷输入，但是$ $中不行，这个环境是我主要用的，一直无法快捷输入有点郁闷。。

**Comment by long-zm123** [comment]
我也遇到了同样的问题，请问解决了吗？
