### ISSUE TITLE
.hsnips 文件生效问题

### ISSUE THREAD

**Issue by turbodog03** [OrangeX4/OrangeX4-HyperSnips#18]
### 建议在 readme文件中增加运行`hsnips.reloadSnippets`命令的说明
您好，我发现在我的 pc 上，照 readme 的方法安装好插件，放好 .hsinps 文件后插件也无法生效，直到查看插件的命令项，发现了`hsnips.reloadSnippets` 项并执行，插件才能正常运行。我在想或许也会有人遇到和我一样的问题，如果把这一条写进 readme 可能会帮助到其他的人。

**Comment by OrangeX4** [comment]
好的，不过这个也可以通过重启 vscode 解决
