### ISSUE TITLE
VS Code 自动补全括号和 HyperSnips @( @[ @{ @< 冲突

### ISSUE THREAD

**Issue by Mrered** [OrangeX4/OrangeX4-HyperSnips#19]
VS Code 中的 `autoClosingBrackets` 设置会导致在输入以下触发词时触发失败：

```markdown
@(
@[
@{
@<
```

建议改成

```markdown
@)
@]
@}
@>
```

或

```markdown
\)
\]
\}
\>
```

或其他能从根本上解决的方法。

感谢！

**Comment by OrangeX4** [comment]
这个解决方案也不错，我之后会改一下的



---原始邮件---
发件人: "Mrered ***@***.***&gt;
发送时间: 2023年4月18日(周二) 中午11:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [OrangeX4/OrangeX4-HyperSnips] VS Code 自动补全括号和 HyperSnips @( @[ @{ @< 冲突 (Issue #19)




 
VS Code 中的 autoClosingBrackets 设置会导致在输入以下触发词时触发失败：
 @( @[ @{ @<
 
建议改成
 @) @] @} @&gt;
 
或
 \) \] \} \&gt;
 
或其他能从根本上解决的方法。
 
感谢！

**Comment by OrangeX4** [comment]
已改，感谢。
