### ISSUE TITLE
制作Beamer时，frame环境中会触发该自动补全

### ISSUE THREAD

**Issue by YanMing-lxb** [OrangeX4/OrangeX4-HyperSnips#22]
在制作Beamer时，在framer环境中会触发HyperSnips的命令，这样的话在写Beamer的时候就很麻烦

**Comment by OrangeX4** [comment]
我 beamer 用的不多，请问能提供一个具体的例子么？


方盛俊
***@***.***

南京大学
学生


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OrangeX4/OrangeX4-HyperSnips"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月11日(星期四) 下午2:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[OrangeX4/OrangeX4-HyperSnips] 制作Beamer时，frame环境中会触发该自动补全 (Issue #22)





 
在制作Beamer时，在framer环境中会触发HyperSnips的命令，这样的话在写Beamer的时候就很麻烦

**Comment by YanMing-lxb** [comment]
你好！

我刚刚排查了一下，发现不是beamer的原因。
在环境中输入" \\[5pt]" 命令，之后的所有环境中都会触发自动补全，包括figure table minipage等环境……

最小示例如下：

\documentclass[aspectratio=43]{beamer}
\usepackage{hyperref}
\usepackage[T1]{fontenc}

\author{YanMing}
\title{TEST}
\subtitle{test}
\institute{Institute}
\date{\today}

\begin{document}

\begin{frame}
    \titlepage % 插入标题
\end{frame}

\begin{frame}
    \\[5pt] 
\end{frame}

\begin{frame}
   该处会触发自动补全
\end{frame}
\end{document}

**Comment by OrangeX4** [comment]
原因是 `\[ \]` 的 `\[` 之后会被识别为数学公式，但是这里的 `\[5pt]` 却只有 `\[` 没有 `\]` 导致没有闭合，我不太理解这个语法的设计原则为什么是这样的，你能否想办法让它在哪个地方加上 `\]` 闭合一下？

**Comment by YanMing-lxb** [comment]
好的，我解决了，在`\\[5pt]`之间加上空格就好了！
`& & & & & $0.173^*$ & $90.64^*$ \\ [5pt]` 这个是我写的表格中的一块，用来增加表格间距，之前中间没用空格分开，所以出现了上述情况

**Comment by YanMing-lxb** [comment]
非常感谢您的帮助！

**Comment by OrangeX4** [comment]
好的，解决了就好
