### ISSUE TITLE
在 quarto 编辑环境下， iAm 疑似会失效。

### ISSUE THREAD

**Issue by ChoCho66** [OrangeX4/OrangeX4-HyperSnips#24]
在 quarto 编辑环境下（rmd 也一樣），snippet 的 iAm 中的数学环境会失效。
例如
```
snippet `\b([A-Z])\1\b` "mathbb X by XX" iAm
\\mathbb ``rv=m[1]``
endsnippet
```
直接打 `PP` 会替换成 `\mathbb P` （不在数学环境内）。

---

但在 markdown 编辑环境下，iAm 中的数学环境是正常的。

之前都可以运作的，不知道是不是前几天的更新导致这现象？
（我安装之前的版本也出现同样现象）。

**Comment by OrangeX4** [comment]
能给出一个可以复现的例子吗，包括一个包含 quarto 编辑环境下的简单文档

**Comment by ChoCho66** [comment]
文档是一般文字档就行了（应该是要安装 quarto 的 extension）
狀況是下面的 gif
我一开始是 **markdown** 编辑环境
我打 `AA`，在没有数学环境下他不会切换到 `\mathbb A`

而后面我切换到 quarto 编辑环境
我打 `AA` 时，没有数学环境下他依旧直接切换成 `\mathbb A`
![asd](https://github.com/OrangeX4/OrangeX4-HyperSnips/assets/72805700/0f9c8035-1b4a-4322-9ba4-9692885bc233)
