### ISSUE TITLE
有时无法触发

### ISSUE THREAD

**Issue by long-zm123** [OrangeX4/OrangeX4-HyperSnips#25]
本人昨天安装时非常的好用，但是今天有好多片段都无法触发了，只有行内和行间公式可以快速的触发，其它的片段都无法触发了，求大神的帮助指导，成分感谢。同时也非常感谢作者的大力开发与维护，谢谢你。
本人电脑安装了Python3.0
本人刚来guithub网站，请多多担待。

**Comment by long-zm123** [comment]
又发现comma命令在第一个（第一次使用时）$ $内无法触发，但是在第二个（紧跟上面无法触发的$comma$后）$ $可以触发。另外comma命令在普通文本模式里面可以正常触发。即$comma$无法正常触发，$comma$$comma$第二个可以正常触发。

**Comment by long-zm123** [comment]
数学环境的限制不起作用，求大神指导

**Comment by OrangeX4** [comment]
检查一下是不是哪里写错了，或者给出一个最小的可复现示例

**Comment by long-zm123** [comment]
comma在两个$符号之间无法触发，但是在普通文本里面又可以触发，
comma片段的触发是iAm

**Comment by long-zm123** [comment]
> 又发现comma命令在第一个（第一次使用时）$ 内无法触发，但是在第二个（紧跟上面无法触发的内无法触发，但是在第二个（紧跟上面无法触发的后）$ 可以触发。另外命令在普通文本模式里面可以正常触发。即可以触发。另外comma命令在普通文本模式里面可以正常触发。即无法正常触发，$comma$$comma$第二个可以正常触发。

**Comment by OrangeX4** [comment]
请给出一个最小的可复现示例

**Comment by long-zm123** [comment]
你好大佬，感谢你的回复！我使用的是latex，配置正确，片段也是复制您的，下面是一个可以复现的例子。$//$------>$//$$$//$$------->$$＼frac{}{}$$普通文本里面 //-------->＼frac{}{}发自我的平板-------- 原始邮件 --------发件人： OrangeX4 ***@***.***>日期： 2023年5月31日周三 23:48收件人： OrangeX4/OrangeX4-HyperSnips ***@***.***>抄送： long-zm123 ***@***.***>, Comment ***@***.***>主    题： Re: [OrangeX4/OrangeX4-HyperSnips] 有时无法触发 (Issue #25)
请给出一个最小的可复现示例

**Comment by OrangeX4** [comment]
你这写的我完全看不懂啊。。。麻烦能不能用 markdown 的格式认真表述一下啊，比如说 `这是代码段`

```text
这也是代码段
```
