### ISSUE TITLE
插件无法生效问题

### ISSUE THREAD

**Issue by xiong-zx** [OrangeX4/OrangeX4-HyperSnips#32]
我同时安装了LaTex language support，LaTeX Workshop，Control Snippets和HyperSnips for Math，并且没有安装HyperSnips插件。但是HyperSnips for Math插件始终无法生效。通过Control Snippets插件只能管理LaTex language support，LaTeX Workshop，但是无法识别HyperSnips for Math。请问该如何解决？

**Comment by OrangeX4** [comment]
我不太明白你的问题，Control Snippets 是什么，这个和 hypersnips 没有关系吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月16日(周一) 上午7:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [OrangeX4/OrangeX4-HyperSnips] 插件无法生效问题 (Issue #32)




 
我同时安装了LaTex language support，LaTeX Workshop，Control Snippets和HyperSnips for Math，并且没有安装HyperSnips插件。但是HyperSnips for Math插件始终无法生效。通过Control Snippets插件只能管理LaTex language support，LaTeX Workshop，但是无法识别HyperSnips for Math。请问该如何解决？
