### ISSUE TITLE
关于行间公式snippet的建议

### ISSUE THREAD

**Issue by pilgrimlyieu** [OrangeX4/OrangeX4-HyperSnips#6]
在markdown.hsnips的403-413行中的im为

```snippets
snippet im "inline Math" wA
$${1}$``
let str = t[0];
let test = str.charAt(str.length - 1);
if (test != ',' &&  test != '.' &&  test != '-' && test !='?' && test !=' '){
	rv = ' ';
}
else{
	rv = '';
}``$2
endsnippet
```

这个snippet只有在$a-$xxx等时$和xxx之间才会没有空格，但是我认为$a$-xxx在$和-之间没有空格的观感更好，而且那位神级小哥似乎也是这么做的:smile:

我自己改了一下不知道对不对。我把`t[0]`改成了`t[1]`，`str.length - 1`改成了`0`。

```snippets
snippet im "inline Math" wA
$${1}$``
let str = t[1];
let test = str.charAt(0);
if (test != ',' &&  test != '.' &&  test != '-' && test !='?' && test !=' '){
	rv = ' ';
}
else{
	rv = '';
}``$2
endsnippet
```

---

还有一个，在559-561行中的是

```snippets
snippet prod "product" wAm
\prod_{${1:n=${2:1}}}^{${3:\infty}} ${4:${VISUAL}} $0
endsnippet
```

请问一下这个`VISUAL`怎么使用，是先框选然后直接输入snippet吗？我试了一下似乎不奏效。

非常感谢！

**Comment by pilgrimlyieu** [comment]
嗯还有一个，以im开头的单词还是挺多的，所以建议可以换成lm之类的。

**Comment by pilgrimlyieu** [comment]
再请教一下，我想让下面这些函数可以在后面为字母时自动添加空格，在非字母时不添加空格，于是我参考了一下im snippet的写法写了下面的snippet，但是只能用一次，嵌套了就无法使用；而且有BUG，会把后面的一个字符拉到前面来。

```snippets
snippet `(?<!\\[a-zA-Z]*)(sin|cos|tan|cot|arcsin|arccos|arctan|arccot|csc|sec|log|ln|lg|exp|arg|max|min)` "函数名" wAm
\``rv = m[1]````
if (/^[a-zA-Z]/.test(t[0]) == true){
	rv = ' ';
}
else{
	rv = '';
}``$1
endsnippet
```

![3](https://user-images.githubusercontent.com/80107081/130614123-1d4c82db-08ea-4ae8-a7a3-a0de45382ea1.gif)

我还写了一个别的，但是也有一样的问题

```snippets
snippet `(?<!\\[a-zA-Z]*)(sin|cos|tan|cot|arcsin|arccos|arctan|arccot|csc|sec|log|ln|lg|exp|arg|max|min)` "函数名" wAm
\``rv = m[1]````
let str = t[0];
let test = str.charAt(0);
if ((test >= "a" && test <= "z") || (test >= "A" && test <= "Z")){
	rv = ' ';
}
else{
	rv = '';
}``$1
endsnippet
```

**Comment by pilgrimlyieu** [comment]
> 再请教一下，我想让下面这些函数可以在后面为字母时自动添加空格，在非字母时不添加空格，于是我参考了一下im snippet的写法写了下面的snippet，但是只能用一次，嵌套了就无法使用；而且有BUG，会把后面的一个字符拉到前面来。

测试了一下，输入依次输入`sin``a``cos`就正常，看来是因为第二个符号snippet触发变成\开头，然后中间的空格就消失了造成的。但是不能排除\，因为空格会阻拦分式snippet的运行（加括号有点麻烦，而且之前好像出过一点bug就没怎么用过）。

还有，依次输入`sin``a``cos`也不会把后一个字符拉到前面了。

不知道有没有一个功能能输完一个字符就自动退出placeholder或者已经有了rv后就不再改变之类的功能。

**Comment by pilgrimlyieu** [comment]
有个小问题，正则排除了一部分，改成下面就可以连续输入命令了。但是没有实质改变，两个问题仍然存在。

```snippets
snippet `(?<!\\)(sin|cos|tan|cot|arcsin|arccos|arctan|arccot|csc|sec|log|ln|lg|exp|arg|max|min)` "函数名" wAm
\``rv = m[1]````
if (/^[a-zA-Z]/.test(t[0]) == true){
	rv = ' ';
}
else{
	rv = '';
}``$1
endsnippet
```

另外，先输入`sin`变成`\sin`后输入`c`按一下<kbd>Tab</kbd>再输入`os`就能正常工作，但是效率太低了。

**Comment by pilgrimlyieu** [comment]
请教一下，我想将类似"$xxx$"替换成"\(xxx\)"，但是"xxx"里包含"$"，然后返回rv时会被当做tab stop，怎样避免这种情况？

代码如下

```snippets
snippet `\$(.+)\$` "test" A
rv = "\\(" + m[1] + "\\)";
endsnippet
```

我也试过将"$"替换成"\$"和"\\$"但没什么用，只要将"$"替换成别的字符就能正常使用，但就是不能正确返回$字符。

非常感谢！！！

**Comment by OrangeX4** [comment]
这是正则表达式的问题, 既然 xxx 包含 "$", 那正则表达式怎么可能那么智能的知道到底要在哪个 "$" 截断呢?

例如 "$abcd$efg$" 这样的字符串, 正则表达式怎么区分得了你要的 xxx 到底是 "abcd" 还是 "abcd$efg" 呢, 两者的区别是非贪婪或贪婪策略.
